
begin

INSERT INTO expensecontrol.materialadddetail
            (billno, item, billid, partnumber,
             description, brand, spec, unitcode, originplace, vencode1,
             singlename1, price1, delivedate1, chsflag1, vencode2,
             singlename2, price2, delivedate2, chsflag2, price3, delivedate3,
             chsflag3, transactor,
             tradate,
             remark, materialtypeid, billpro, statype, billsta, picqty,
             istax1, istax2, profitloss, returnvar
            )
     VALUES ('MA201606290003', 1, 'MA2016062900031', '0602019-0222064',
             '倒角刀', '訂制', '602H-DJ612,鑽石', '支', '中國', 'VCN0000190',
             '基準龍華分', 1346, 0, 'Y', 'VCN0000192',
             'JINCHENG H', 1346, 0, 'Y', 0, 0,
             'N', 'F0804378',
             TO_DATE ('07/05/2016 11:59:30', 'MM/DD/YYYY HH24:MI:SS'),
             '新增料號,附件1第1項', '0602019-022', 'MA', 'D', 'CL', 0,
             'N', 'N', 6, 'N'
            );
			
INSERT INTO expensecontrol.materialadddetail
            (billno, item, billid, partnumber,
             description, brand, spec, specdesc, unitcode, originplace,
             vencode1, singlename1, price1, delivedate1, chsflag1, vencode2,
             singlename2, price2, delivedate2, chsflag2, price3, delivedate3,
             chsflag3, transactor,
             tradate,
             remark, materialtypeid, billpro, statype, billsta, picqty,
             istax1, istax2, profitloss, returnvar
            )
     VALUES ('MA201606290003', 2, 'MA2016062900032', '0602019-0815712',
             '銑刀', '訂制', '602H-DJ615,鑽石', '規格型號', '支', '中國',
             'VCN0000190', '基準龍華分', 1645, 0, 'Y', 'VCN0000192',
             'JINCHENG H', 1645, 0, 'Y', 0, 0,
             'N', 'F0804378',
             TO_DATE ('07/05/2016 11:59:31', 'MM/DD/YYYY HH24:MI:SS'),
             '新增料號,附件1第2項', '0602019-081', 'MA', 'D', 'CL', 0,
             'N', 'N', 6, 'N'
            );
COMMIT ;



INSERT INTO expensecontrol.materialaddmaster
            (billno,
             applydate, billpro,
             billsta, applicant, areacode, companyid, depcode, tel,
             mail, currcode, itemqty, transactor, apprcode, pricode,
             statype, docqty, divisiongroup, division,
             senddate, tranareacode,
             isflag, property
            )
     VALUES ('MA201606290003',
             TO_DATE ('06/29/2016 08:13:40', 'MM/DD/YYYY HH24:MI:SS'), 'MA',
             'CL', 'F0804378', 'LH', '000081', 'T30007', '568-70826',
             'hzlh-st-mp12@mail.foxconn.com', 'RMB', 7, 'F2162276', 'E', 'B',
             'M', 2, 'SHZBG事業群', 'ST產品處',
             TO_DATE ('06/30/2016 10:12:49', 'MM/DD/YYYY HH24:MI:SS'), 'LH',
             '1', '2'
            );
COMMIT ;

end;


----------------------
 
Insert into MATERIALMASTER
   (PARTNUMBER, PROPERTY, TYPECODE1, DESCRIPTION1, TYPECODE2, DESCRIPTION2, TYPECODE3, DESCRIPTION3, TYPECODE4, TYPEID, DESCRIPTION, BRAND, SPEC, ORIGINPLACE, UNITCODE, BIDCODE, PURCODE, ACCCODE, INVMETCODE, FLAG, APPLICANT, APPLYDATE, TRADATE, REMARK, LOCKFLAG, SUBTAXRATE, PROFITLOSS, MOVEFLAG)
 Values
   ('0602019-0222064', '2', '06', '加工/檢測耗材', '02', '切削類刀具', '019', '銑削刀具', '022', '0602019-022', '倒角刀', '訂制', '602H-DJ612,鑽石', '中國', '支', 'G', 'G', '21', 'G', 'Y', 'F0804378', TO_DATE('06/29/2016 08:13:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/05/2016 11:59:30', 'MM/DD/YYYY HH24:MI:SS'), '新增料號,附件1第1項', 'N', 0, 6, 'N');
COMMIT;

----------------------

SET DEFINE OFF;
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'AQ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'BH', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'BJ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'CD', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'CQ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'CS', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'ED', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'FC', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'FN', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'FS', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'GY', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'GZ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H1', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H2', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H3', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H4', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H5', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H6', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H7', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'H8', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HA', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HB', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HC', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HD', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HS', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HU', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HY', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'HZ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'JC', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'JS', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'JY', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'KS', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'LF', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, STARTDATE, ENDDATE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, DUTYUSER, DUTYDEPT, COMPANYID, KEEPTIMES)
 Values
   ('0602019-0222064', 'LH', 'G', TO_DATE('07/05/2016 13:33:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('10/05/2016 13:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'G', 'G', 'Y', 0, '3', 'COST', 'N', 0, '1', 0, 'N', '中國', 'F0804378', 'T30007', '000081', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'NJ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'NN', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'NY', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'NZ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'QH', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'SH', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'SY', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'TJ', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'TY', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'WH', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'YC', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'YF', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'YK', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'YT', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
Insert into MATERIALREGION
   (PARTNUMBER, AREACODE, BIDCODE, PURCODE, INVMETCODE, FLAG, SUBTAXRATE, APPLYFLAG, KINDID, HAVEREMARK, RETURNRATEVAR, PAYKIND, PAYPERIOD, ISCHECK, ORIGINCOUNTRY, KEEPTIMES)
 Values
   ('0602019-0222064', 'ZU', 'G', 'G', 'G', 'N', 0, '3', 'COST', 'N', 1, '1', 0, 'N', '中國', 0);
   
COMMIT;

-----------------------------

SET DEFINE OFF;
Insert into MATERIALVENDOR
   (PARTNUMBER, VENCODE, SINGLENAME, CURRCODE, RATE, PRICE, HUBVENDOR, DELIVEDATE, CREATOR, CREATEDATE, FLAG, COMPANYID, ISTAX)
 Values
   ('0602019-0222064', 'VCN0000190', '基準龍華分', 'RMB', 1, 1346, 'G', 0, 'F0804378', TO_DATE('07/05/2016 13:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'LH', 'N');
Insert into MATERIALVENDOR
   (PARTNUMBER, VENCODE, SINGLENAME, CURRCODE, RATE, PRICE, HUBVENDOR, DELIVEDATE, CREATOR, CREATEDATE, FLAG, COMPANYID, ISTAX)
 Values
   ('0602019-0222064', 'VCN0000192', 'JINCHENG H', 'RMB', 1, 1346, 'G', 0, 'F0804378', TO_DATE('07/05/2016 13:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'LH', 'N');
COMMIT;
